CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    name TEXT NOT NULL
    );

CREATE TABLE relation (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    user_id INTEGER REFERENCES[users],
    friend_id INTEGER REFERENCES[users]
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    sender_id INTEGER REFERENCES[users],
    recipient_id INTEGER REFERENCES[users],
    content TEXT NOT NULL
);