CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL
    );

CREATE TABLE relation (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users,
    friend_id INTEGER NOT NULL REFERENCES users
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    sender_id INTEGER NOT NULL REFERENCES users,
    recipient_id INTEGER NOT NULL REFERENCES users,
    content TEXT NOT NULL
);